// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1apgW7qXTnvEjaSg1iUL0ZGI1VZkR9Ps',
    appId: '1:402733687545:web:98338cc05965d99bbe3828',
    messagingSenderId: '402733687545',
    projectId: 'sandur-fresh',
    authDomain: 'sandur-fresh.firebaseapp.com',
    storageBucket: 'sandur-fresh.firebasestorage.app',
    measurementId: 'G-E77S37SR63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7RR73nIN-N7bm7AIB5eCXOiR3kYaeOz0',
    appId: '1:402733687545:android:8a89f34a8be8cbf3be3828',
    messagingSenderId: '402733687545',
    projectId: 'sandur-fresh',
    storageBucket: 'sandur-fresh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg7as7xClE0oF4YcwKYVJULxssIpcFY0U',
    appId: '1:402733687545:ios:e485e967efeb1628be3828',
    messagingSenderId: '402733687545',
    projectId: 'sandur-fresh',
    storageBucket: 'sandur-fresh.firebasestorage.app',
    iosBundleId: 'com.example.sfCustomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg7as7xClE0oF4YcwKYVJULxssIpcFY0U',
    appId: '1:402733687545:ios:fa1950d906cdcd91be3828',
    messagingSenderId: '402733687545',
    projectId: 'sandur-fresh',
    storageBucket: 'sandur-fresh.firebasestorage.app',
    iosBundleId: 'com.binyoga.smart',
  );
}
