// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMvzgvmtGs6udBJ_HJTk7D99gFzc9rn2A',
    appId: '1:238470682380:web:5e027cf079359000a9db29',
    messagingSenderId: '238470682380',
    projectId: 'sandur-fresh-2e53d',
    authDomain: 'sandur-fresh-2e53d.firebaseapp.com',
    storageBucket: 'sandur-fresh-2e53d.firebasestorage.app',
    measurementId: 'G-GVDXM73F6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr_sJD1VhtP9tqUc3AO82O-V0qnZmVT_4',
    appId: '1:238470682380:android:c14533ffcd129a8da9db29',
    messagingSenderId: '238470682380',
    projectId: 'sandur-fresh-2e53d',
    storageBucket: 'sandur-fresh-2e53d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP8GVCdRQ8YfbG-6Phr6L2wpOLIYpnaM8',
    appId: '1:238470682380:ios:405ec2be07242209a9db29',
    messagingSenderId: '238470682380',
    projectId: 'sandur-fresh-2e53d',
    storageBucket: 'sandur-fresh-2e53d.firebasestorage.app',
    iosBundleId: 'com.example.sfCustomer',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP8GVCdRQ8YfbG-6Phr6L2wpOLIYpnaM8',
    appId: '1:238470682380:ios:52fe5fc65e3a3a92a9db29',
    messagingSenderId: '238470682380',
    projectId: 'sandur-fresh-2e53d',
    storageBucket: 'sandur-fresh-2e53d.firebasestorage.app',
    iosBundleId: 'com.binyoga.smart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMvzgvmtGs6udBJ_HJTk7D99gFzc9rn2A',
    appId: '1:238470682380:web:74f10f233709af4aa9db29',
    messagingSenderId: '238470682380',
    projectId: 'sandur-fresh-2e53d',
    authDomain: 'sandur-fresh-2e53d.firebaseapp.com',
    storageBucket: 'sandur-fresh-2e53d.firebasestorage.app',
    measurementId: 'G-8XV7QCPC4X',
  );
}
