targets:
  $default:
    builders:
      graphql_codegen:
        options:
          assets:
            - lib/graphql/queries/**.graphql
          schema: lib/graphql/schema.graphql
          outputDirectory: ../generated
